name: Docker Image Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Docker
      run: echo "${{ secrets.DOCKER_USER }}" | docker login -u "${{ secrets.DOCKER_PASS }}" --password-stdin
    - name: Pull Docker Image
      run: docker pull <krl221/compose:first>
    - name: Push to GitHub
      run: git add <krl221/compose:first> && git commit -m "add image" && git push
